### ISSUE TITLE
Relevant references or theoretical support

### ISSUE THREAD

**Issue by pancratm** [WuYunjin/Hierarchical-Causal-Clustering#1]
Hello, I’m a postgraduate student in the research direction of medical informatics. I‘m very interested in causal clustering and have recently read some relevant literature. Do you have corresponding references or theoretical support for this code? I hope to read the literature to further understand.  I would be very grateful if you can provide it.
Wish for your reply. 
Thanks.

**Comment by WuYunjin** [comment]
> Hello, I’m a postgraduate student in the research direction of medical informatics. I‘m very interested in causal clustering and have recently read some relevant literature. Do you have corresponding references or theoretical support for this code? I hope to read the literature to further understand. I would be very grateful if you can provide it. Wish for your reply. Thanks.

Hi, Thanks for being interested in this work. The corresponding paper (which is a Chinese paper) for this code is still under review and it will be available soon (in this month I guess).
If you are interested in causal clustering, maybe you would like to read this paper(CCSL: A Causal Structure Learning Method from Multiple Unknown Environments, https://arxiv.org/abs/2111.09666), which is also for causal clustering but based on the Chinese Restaurant Process.

**Comment by pancratm** [comment]
Thank you very much! Look forward to your publication.

**Comment by pancratm** [comment]
> > Hello, I’m a postgraduate student in the research direction of medical informatics. I‘m very interested in causal clustering and have recently read some relevant literature. Do you have corresponding references or theoretical support for this code? I hope to read the literature to further understand. I would be very grateful if you can provide it. Wish for your reply. Thanks.
> 
> Hi, Thanks for being interested in this work. The corresponding paper (which is a Chinese paper) for this code is still under review and it will be available soon (in this month I guess). If you are interested in causal clustering, maybe you would like to read this paper(CCSL: A Causal Structure Learning Method from Multiple Unknown Environments, https://arxiv.org/abs/2111.09666), which is also for causal clustering but based on the Chinese Restaurant Process.

Sorry to bother you again. The article you provided was a great help to me. 
I would like to ask if "time series" data is necessary in the paper? The second example in real-world dosen't seem to be time series data and I can't understand why using time series in the model premise. 
Besides, Causal clustering seems to have been around since 2018-19, and there aren't many open source documents on the subject. I wonder if there is open source code for that article at present? Or some other basic framework code that can help.  At the end of that article, the author proposed that the model is only applicable to linear non-Gaussian assumptions, and I hope to modify it on this basis and apply the model to medical data.

Wish for your reply.
Thanks a lot.

**Comment by WuYunjin** [comment]
> > > Hello, I’m a postgraduate student in the research direction of medical informatics. I‘m very interested in causal clustering and have recently read some relevant literature. Do you have corresponding references or theoretical support for this code? I hope to read the literature to further understand. I would be very grateful if you can provide it. Wish for your reply. Thanks.
> > 
> > 
> > Hi, Thanks for being interested in this work. The corresponding paper (which is a Chinese paper) for this code is still under review and it will be available soon (in this month I guess). If you are interested in causal clustering, maybe you would like to read this paper(CCSL: A Causal Structure Learning Method from Multiple Unknown Environments, https://arxiv.org/abs/2111.09666), which is also for causal clustering but based on the Chinese Restaurant Process.
> 
> Sorry to bother you again. The article you provided was a great help to me. I would like to ask if "time series" data is necessary in the paper? The second example in real-world dosen't seem to be time series data and I can't understand why using time series in the model premise. Besides, Causal clustering seems to have been around since 2018-19, and there aren't many open source documents on the subject. I wonder if there is open source code for that article at present? Or some other basic framework code that can help. At the end of that article, the author proposed that the model is only applicable to linear non-Gaussian assumptions, and I hope to modify it on this basis and apply the model to medical data.
> 
> Wish for your reply. Thanks a lot.

Hi, Sorry for the late reply. The time series data is not necessary and the proposed method can be applied to non-temporal data by setting time-lag to **0**. Since the causal relations considered by the proposed method include the instantaneous causal relations and lagged causal relations. The source code for the CCSL model is not public yet,  I would let you know as long as it is available.
 
Thanks

**Comment by pancratm** [comment]
Thank you very much for your reply!
Recently I have another problem. For causal clustering of real data of unknown clusters, which indicators should be used to evaluate the quality of clustering? Can I just use silhouette_score to evaluate like the normal cluster algorithm based on distance metric?

**Comment by WuYunjin** [comment]
> Thank you very much for your reply! Recently I have another problem. For causal clustering of real data of unknown clusters, which indicators should be used to evaluate the quality of clustering? Can I just use silhouette_score to evaluate like the normal cluster algorithm based on distance metric?

That's a good question and I am not sure either. Since we could cluster samples from different defined distances and may lead to different results. In my understanding, causal clustering tries to measure the distance of samples from the perspectives of causality (or generative mechanism) while the common clustering methods(e.g. KMeans with euclidean distance) measure the distance of samples from the perspectives of euclidean distance. 
The silhouette_score may prefer the euclidean-distance-based clustering to causal clustering since the default metric of the
silhouette_score is euclidean distance.

**Comment by WuYunjin** [comment]
Update the paperlink and quickstart command of this repo in the readme
